config/routes.rb
Rails.application.routes.draw do
  get 'ajax/:action', to: 'ajax#:action', :defaults => { :format => 'json' }
  get 'home/index'

  namespace :api do
    get '/user', to: '/api/user#data'
    get '/user/bids', to: '/api/user#user_bids'
    patch '/user/update', to: '/api/user#user_data_update'
  end

  devise_for :users
  root 'home#index'
  get 'product/id'
  get '/products/won'    ,to: 'bids#won', as: 'won_bids'

  
  get '/purchased/products', to: 'bids#purchased_items', as: 'purchased'
  resources :products 

  # get 'something', to: 'controller#action', as: 'something'

  get "rejected/bids", to: 'bids#rejected', as: 'rejected'

  post "cards/:id" => "checkout#create_card", as: :create_payment_method

  get 'bids/:id/payment', to: 'checkout#create', as: 'payment'

  put 'bids/:id/accept' , to: 'bids#accept', as: 'accept_bid'

  get 'bids/:id', to: 'bids#bid_accept_by_buyer', as: 'purchase_item'

  get 'bids', to: 'bids#show', as: 'user_bids'

  get 'history', to: 'payment#transaction', as: 'payment_history'


  get '/products/:product_id/bids' , to: 'bids#index', as: 'product_bids'
  
  get '/products/:product_id/bids/new', to: 'bids#new', as: 'new_product_bid'

  post '/products/:product_id/bids', to: 'bids#create', as: 'create_bid'

  get '/sold/products', to: 'bids#sold_items', as: 'sold_item'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :product
  belongs_to :user

  def bidaccept 
    self.status = true
    self.updated_at = Time.now
    self.save
  end

  def self.valid(bid)
    @initial_price = bid.product.starting_bid
    if bid.current_bid.present? && bid.current_bid > @initial_price && bid.current_bid > ApplicationRecord.maximum_bid(bid.product_id)
      return true
    else
      return false
    end
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user!

  def index 
    @bids = Bid.where(product_id: params[:product_id]).order(current_bid: :desc)
  end

  def show 
    @bids = current_user.bids.order(current_bid: :desc)
  end

  def new 
    @bid = current_user.bids.new
  end

  def create
    @bid = current_user.bids.new(product_id:product_param[:product_id],current_bid:bid_params[:current_bid])
    
    if Bid.valid(@bid)
      @bid.save
      redirect_to product_bids_path, flash:{ notice:"Bid has been Created, Thanks!"}
    else 
      redirect_to new_product_bid_path, flash:{ alert:"Please enter a valid Bid!"}
    end
  end

  def accept 
    @bid = Bid.find_by_id(params[:id])
    @bid.bidaccept
    redirect_to home_index_path, flash:{ notice:"Bid has been Accepted, Thanks!"}
  end

  def bid_accept_by_buyer 
    bid = Bid.find_by_id(params[:id])
    @email = bid.product.user.email

    #  To change the price with current bid
    product = Product.find_by_id(bid.product_id)
    product.price = bid.current_bid
    product.save

    # bid.product.price = bid.current_bid
    GuestJob.perform_later(@email)
    redirect_to home_index_path, flash:{ notice:"Item has been Purchased, Thanks!"}
  end

  def won 
    bid = current_user.bids.all
    @bid = bid.where(status: true)
  end

  def purchased_items 
    @item = current_user.bids.where(status: true)
  end

  def rejected 
    bid = current_user.bids.all
    @bid = bid.where(rejection: true)
  end

  def sold_items 
    @items = current_user.products.where.not(price: nil)
  end

  private

  def bid_params
    params.require(:bid).permit(:current_bid,:product_id)
  end

  def product_param
    params.permit(:product_id)
  end
end

app/helpers/bids_helper.rb
module BidsHelper
  def seconds_to_hms(sec)
    "%02d:%02d:%02d" % [sec / 3600, sec / 60 % 60, sec % 60]
  end
end

app/views/bids/_form.html.erb
<%= form_with model: bid, url: create_bid_path do |form| %>
<div class ="row">
  <div class="col-lg-4">
    <div class="form-group">
    <%= form.label:your_bid,class:'mb-2' %>
    <%= form.text_field:current_bid,class:'form-control form-control-lg' %>
    <% bid.errors.full_messages_for(:current_bid).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <%end%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12 mt-4">
  <%=form.submit class:'btn btn-primary btn-lg'%>
  <%=link_to "Back to Bids",product_bids_path,class:"btn btn-outline-primary btn-lg"%>
</div>
</div>
<%end%>
</div>

app/views/bids/index.html.erb
<div class = "d-flex justify-content-center">
    <h1> Latest Bids </h1>
</div>

<% if current_user.id !=  Product.find_by_id(params[:product_id]).user_id && show_helper(params[:product_id]) == true %>
  <a class="btn btn-primary" href="<%= new_product_bid_path(product_id: params[:product_id]) %>" role="button">Make a Bid</a>
<% end %>

<% index_helper %>

<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Latest Price</th>
    <th>Quantity</th>
    <% if index_check(@bids) == true %> 
      <th>Accept Bid</th>
    <% end %>   
    <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.product.name %></td>
        <td><%= bid.current_bid %></td>
        <td><%= bid.product.quantity %></td>
        <% if index_check(@bids) == true %>
          <td>
            <%= index_accept(bid) %>
          </td>
        <% end %>
        <% if bid_accept_check(bid) == true %>
          <td>Accepted</td>
        <% elsif bid_reject_check(bid) == true %>
          <td>Not Accepted</td>
        <% else %>
          <td>Open for Auction</td>
        <% end %>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/bids/new.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5">
  <div class="card-body">
  <h2 class="text-center">Create New Bid</h2>
  <h5 class="text-center">Current Highest Bid : 
  <% maxbid = ApplicationRecord.maximum_bid(params[:product_id]) %>
  <% if maxbid == 0 %> Item has No Bids
  <% else %>
  <%= maxbid %>
  <% end%>
  </h5>
  </div>
</div>
<%=render 'form', bid: @bid %>

app/views/bids/purchased_items.html.erb
<div class="card mt-5 mb-5">
  <div class="card-body">
    <h2 class="text-center"> Your Purchased Items</h2>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Starting Price</th>
    <th>Quantity</th>
    <th>Highest Bid</th>
    </tr>
  </thead>
  <tbody>
    <% @item.each do |bid| %>
    <% productid = bid.product_id %>
    <% if  Product.find_by_id(productid).price.present? %>
      <tr>
        <td><%= bid.product.name %></td>
        <td><%= bid.product.starting_bid %></td>
        <td><%= bid.product.quantity %></td>
        <td><%= bid.product.price %></td>
      </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

app/views/bids/rejected.html.erb
<div class="card mt-5 mb-5">
  <div class="card-body">
    <h2 class="text-center"> Your Rejected Bids </h2>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Starting Price</th>
    <th>Your Bid</th>
    <th>Quantity</th>
    </tr>
  </thead>
  <tbody>
    <% @bid&.each do |bid| %>
      <tr>
        <td><%= bid.product.name %></td>
        <td><%= bid.product.starting_bid %></td>
        <td><%= bid.current_bid%>
        <td><%= bid.product.quantity %></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/bids/show.html.erb
<div class="card mt-5 mb-5">
  <div class="card-body">
    <h2 class="text-center"> Your Bids </h2>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Starting Price</th>
    <th>Your Bid</th>
    <th>Quantity</th>
    <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.product.name %></td>
        <td><%= bid.product.starting_bid %></td>
        <td><%= bid.current_bid %>
        <td><%= bid.product.quantity %></td>
        <% if bid_accept_check(bid) %>
          <td>Accepted</td>
        <% elsif bid.rejection == true %> 
           <td>Bid Rejected</td>
        <% elsif bid_reject_check(bid) %>
          <td>Not Accepted</td>
        <% else %>
          <td>Open for Auction</td>
        <% end %>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/bids/sold_items.html.erb
<div class="card mt-5 mb-5">
  <div class="card-body">
    <h2 class="text-center"> Your Sold Items</h2>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Starting Price</th>
    <th>Quantity</th>
    <th>Highest Bid</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.starting_bid %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/bids/won.html.erb
<div class="card mt-5 mb-5">
  <div class="card-body">
    <h2 class="text-center"> Your Won Bids </h2>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Starting Price</th>
    <th>Your Bid</th>
    <th>Quantity</th>
    <th>Ending Time</th>
    <th>Accept and Pay</th>
    </tr>
  </thead>
  <tbody>
    <% @bid.each do |bid| %>
      <% unless bid.product.price.present? %>
      <tr>
        <td><%= bid.product.name %></td>
        <td><%= bid.product.starting_bid %></td>
        <td><%= bid.current_bid%>
        <td><%= bid.product.quantity %></td>
        <td><%= seconds_to_hms((bid.updated_at + 172800) - Time.now) %>
        <% if (bid.updated_at + 172800) - Time.now > 0 %>
            <td>
              <%= form_tag create_payment_method_path(bid), id: "billing-create-payment-method" do  %>
              <%= link_to "Accept and Pay", payment_path(bid), remote: true, class: "btn btn-primary" %>
              <% end %>
            </td>
          <% else %>
            <td>
              <% bid.status = false %>
              <% bid.rejection = true %>
              <% bid.save %>
            </td>
        <% end %>
      </tr>
      <% end %>
    <%end%>
  </tbody>
</table>