config/routes.rb
Rails.application.routes.draw do
  get 'ajax/:action', to: 'ajax#:action', :defaults => { :format => 'json' }
  get 'home/index'

  namespace :api do
    get '/user', to: '/api/user#data'
    get '/user/bids', to: '/api/user#user_bids'
    patch '/user/update', to: '/api/user#user_data_update'
  end

  devise_for :users
  root 'home#index'
  get 'product/id'
  get '/products/won'    ,to: 'bids#won', as: 'won_bids'

  
  get '/purchased/products', to: 'bids#purchased_items', as: 'purchased'
  resources :products 

  # get 'something', to: 'controller#action', as: 'something'

  get "rejected/bids", to: 'bids#rejected', as: 'rejected'

  post "cards/:id" => "checkout#create_card", as: :create_payment_method

  get 'bids/:id/payment', to: 'checkout#create', as: 'payment'

  put 'bids/:id/accept' , to: 'bids#accept', as: 'accept_bid'

  get 'bids/:id', to: 'bids#bid_accept_by_buyer', as: 'purchase_item'

  get 'bids', to: 'bids#show', as: 'user_bids'

  get 'history', to: 'payment#transaction', as: 'payment_history'


  get '/products/:product_id/bids' , to: 'bids#index', as: 'product_bids'
  
  get '/products/:product_id/bids/new', to: 'bids#new', as: 'new_product_bid'

  post '/products/:product_id/bids', to: 'bids#create', as: 'create_bid'

  get '/sold/products', to: 'bids#sold_items', as: 'sold_item'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :bids, dependent: :destroy
    has_one_attached :image
    validates :name, :comapny_name, :phone_number, :bank_account,:description, presence: true
    validates :phone_number, length: {is:10}
    validates :bank_account, length:{is:10}
    validates :description, length:{minimum:25}
    validates :name, uniqueness: true
    validates :starting_bid, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_product, only: [:edit, :destroy, :update]

  def index
    @products = current_user.products.all
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to products_path, flash:{ notice:"Item has been Created, Thanks!"}
    else 
      render :new
    end
  end

  def edit
  end

  def update 
    if @product.update(product_params)
      redirect_to products_path, flash:{notice:"Item Data has been Updated"}
    else 
      render :edit, flash:{notice:"Item has Not been Updated. Please Verify Details"}
    end
  end

  def destroy 
    if @product.destroy
      redirect_to products_path, flash:{notice:"Item has been deleted.Thanks!"}
    end
  end

  private

  def set_product
    @product = Product.find_by(id: params[:id])
    unless @product.present?
      redirect_to products_path, flash:{notice:"Item does not exist"}
    end
  end

  def product_params
    params.require(:product).permit(:name,:your_name,:comapny_name,:description,:bank_account,:image,:quantity,:starting_bid,:expected_bid,:phone_number)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model:product do |form|%>
<div class ="row">
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:product_name,class:'mb-2'%>
    <%=form.text_field:name,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:name).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:your_name,class:'mb-2'%>
    <%=form.text_field:your_name,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:your_name).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:your_company_name,class:'mb-2'%>
    <%=form.text_field:comapny_name,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:comapny_name).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:image,class:'mb-2'%>
    <%=form.file_field:image,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:comapny_name).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:starting_bid,class:'mb-2'%>
    <%=form.text_field:starting_bid,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:starting_bid).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:expected_bid,class:'mb-2'%>
    <%=form.text_field:expected_bid,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:expected_bid).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:description_of_product,class:'mb-2'%>
    <%=form.text_field:description,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:description).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:your_bank_account_number,class:'mb-2'%>
    <%=form.text_field:bank_account,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:bank_account).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:quantity_of_product,class:'mb-2'%>
    <%=form.text_field:quantity,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:quantity).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
    <%=form.label:your_phone_number,class:'mb-2'%>
    <%=form.text_field:phone_number,class:'form-control form-control-lg'%>
    <%@product.errors.full_messages_for(:phone_number).each do |message| %>
    <p class="text-danger"><%=message%></p>
    <%end%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12 mt-4">
  <%=form.submit class:'btn btn-primary btn-lg'%>
  <%=link_to "Back to Auction",products_path,class:"btn btn-outline-primary btn-lg"%>
</div>
</div>
<%end%>
</div>

app/views/products/edit.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5">
  <div class="card-body">
  <h2 class="text-center">Edit Your Item Data</h2>
  </div>
</div>
<%=render 'form',product: @product %>

app/views/products/index.html.erb
<div class="card mt-5 mb-5">
  <div class="card-body">
    <h2 class="text-center"> Your Live Items</h2>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Product Name</th>
    <th>Starting Price</th>
    <th>Quantity</th>
    <th>Highest Bid</th>
    <th>Edit Your Item Info</th>
    <th>Delete Item</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <% if show_helper(product.id) == true %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.starting_bid %></td>
        <td><%= product.quantity %></td>
        <td>
        <% maxbid = ApplicationRecord.maximum_bid(product.id) %>
        <% if maxbid == 0 %> 
          Item has No Bids
        <% else %>
          <%= maxbid %>
        <% end %>
        <br>
        <%= link_to "Enter" ,product_bids_path(product), class:"btn btn-primary" %>
        </td>
        <td>
            <%= link_to "Edit" , edit_product_path(product),class:"btn btn-primary"%>
        </td>
        <td>
            <%= link_to "Delete" ,product_path(product),class:"btn btn-danger",method: :delete,data:{confirm:"Deleting this item will stop the proccess of Bidding. Are you sure you want to delete?"}%>
        </td>
      </tr>
       <% end %>
    <%end%>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="col-lg-12">
<div class="card mt-5 mb-5">
  <div class="card-body">
  <h2 class="text-center">Create New Item</h2>
  </div>
</div>
<%=render 'form',product: @product %>